package roocode

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type CodeGenerator struct {
	outputDir string
}

func NewCodeGenerator(outputDir string) *CodeGenerator {
	return &CodeGenerator{outputDir: outputDir}
}

func (g *CodeGenerator) Generate(ctx context.Context, spec GenerateSpec) (string, error) {
	if err := os.MkdirAll(g.outputDir, 0755); err != nil {
		return "", fmt.Errorf("create output dir: %w", err)
	}

	content := buildContent(spec)
	fileName := spec.Name + fileExtension(spec.Type)
	filePath := filepath.Join(g.outputDir, fileName)

	if err := os.WriteFile(filePath, []byte(content), 0644); err != nil {
		return "", fmt.Errorf("write file: %w", err)
	}

	return filePath, nil
}

func (g *CodeGenerator) Bootstrap(ctx context.Context, spec BootstrapSpec) ([]string, error) {
	dir := spec.OutputDir
	if dir == "" {
		dir = filepath.Join(g.outputDir, spec.Name)
	}
	if err := os.MkdirAll(dir, 0755); err != nil {
		return nil, fmt.Errorf("create project dir: %w", err)
	}

	var files []string

	switch spec.ProjectType {
	case "go":
		mainFile := filepath.Join(dir, "main.go")
		content := fmt.Sprintf("package main\n\nfunc main() {\n\t// %s\n}\n", spec.Name)
		os.WriteFile(mainFile, []byte(content), 0644)
		files = append(files, mainFile)

		goMod := filepath.Join(dir, "go.mod")
		os.WriteFile(goMod, []byte(fmt.Sprintf("module %s\n\ngo 1.24\n", spec.Name)), 0644)
		files = append(files, goMod)

	case "python":
		mainFile := filepath.Join(dir, "main.py")
		content := fmt.Sprintf("#!/usr/bin/env python3\n\"\"\"%s\"\"\"\n\ndef main():\n    pass\n\nif __name__ == \"__main__\":\n    main()\n", spec.Name)
		os.WriteFile(mainFile, []byte(content), 0644)
		files = append(files, mainFile)

	case "node":
		mainFile := filepath.Join(dir, "index.js")
		content := fmt.Sprintf("// %s\n\nfunction main() {\n  console.log(\"Hello\");\n}\n\nmain();\n", spec.Name)
		os.WriteFile(mainFile, []byte(content), 0644)
		files = append(files, mainFile)
	}

	return files, nil
}

func buildContent(spec GenerateSpec) string {
	var b strings.Builder

	switch spec.Type {
	case "go":
		b.WriteString(fmt.Sprintf("package %s\n\n", spec.Template))
		if spec.Prompt != "" {
			b.WriteString(fmt.Sprintf("// %s\n", spec.Prompt))
		}
		b.WriteString(fmt.Sprintf("func %s() {\n\t// TODO: implement\n}\n", spec.Name))
	case "python":
		if spec.Prompt != "" {
			b.WriteString(fmt.Sprintf("# %s\n", spec.Prompt))
		}
		b.WriteString(fmt.Sprintf("def %s():\n    pass\n", spec.Name))
	case "js":
		if spec.Prompt != "" {
			b.WriteString(fmt.Sprintf("// %s\n", spec.Prompt))
		}
		b.WriteString(fmt.Sprintf("function %s() {\n  // TODO: implement\n}\n", spec.Name))
	default:
		b.WriteString(fmt.Sprintf("// %s - generated by Roo-code\n", spec.Name))
	}
	return b.String()
}

func fileExtension(lang string) string {
	switch lang {
	case "go":
		return ".go"
	case "python":
		return ".py"
	case "js", "node":
		return ".js"
	default:
		return ".txt"
	}
}
