// Copyright 2024 HelixCode. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.

/*
Package editor provides a comprehensive multi-format code editing system
optimized for different LLM models in the HelixCode platform.

# Overview

The editor package supports multiple edit formats, automatic format selection based
on LLM model capabilities, built-in validation, backup support, and syntax validation.
It is designed to efficiently process code edits generated by various AI models.

# Edit Formats

The package supports four edit formats, each optimized for different use cases:

EditFormatDiff uses Unix unified diff format for precise, contextual edits:

	editor, _ := editor.NewCodeEditor(editor.EditFormatDiff)
	edit := editor.Edit{
	    FilePath: "test.go",
	    Format:   editor.EditFormatDiff,
	    Content: `--- test.go
	+++ test.go
	@@ -1,3 +1,3 @@
	 line1
	-line2
	+modified line
	 line3`,
	}
	editor.ApplyEdit(edit)

EditFormatWhole replaces the entire file content:

	edit := editor.Edit{
	    FilePath: "config.json",
	    Format:   editor.EditFormatWhole,
	    Content:  `{"key": "new value"}`,
	}

EditFormatSearchReplace performs pattern-based search and replacement:

	edit := editor.Edit{
	    FilePath: "code.go",
	    Format:   editor.EditFormatSearchReplace,
	    Content: []editor.SearchReplace{
	        {Search: "oldFunc", Replace: "newFunc", Count: -1, Regex: false},
	        {Search: `test\d+`, Replace: "exam", Count: -1, Regex: true},
	    },
	}

EditFormatLines edits specific line ranges:

	edit := editor.Edit{
	    FilePath: "file.txt",
	    Format:   editor.EditFormatLines,
	    Content: []editor.LineEdit{
	        {StartLine: 5, EndLine: 7, NewContent: "new\ncontent\nhere"},
	    },
	}

# Model-Specific Format Selection

The package includes intelligent format selection based on LLM model capabilities:

	// Automatic selection
	format := editor.SelectFormatForModel("gpt-4o")        // Returns: EditFormatDiff
	format = editor.SelectFormatForModel("claude-3-sonnet") // Returns: EditFormatSearchReplace

	// Check format support
	supported := editor.SupportsFormat("gpt-4", editor.EditFormatDiff) // Returns: true

	// Get full capabilities
	capability := editor.GetModelCapability("claude-3-opus")

# Supported Models

The package provides optimized format selection for major LLM providers:

OpenAI:
  - GPT-4o, GPT-4 Turbo, GPT-4: Diff format
  - GPT-3.5 Turbo: Search/Replace format
  - O1 Preview/Mini: Whole format

Anthropic:
  - Claude 3 Opus, Sonnet, Haiku: Search/Replace format
  - Claude 3.5 Sonnet, Claude Sonnet 4: Search/Replace format

Google:
  - Gemini Pro: Whole format
  - Gemini Ultra, 1.5 Pro: Diff format
  - Gemini 1.5 Flash: Search/Replace format

Meta:
  - Llama 2/3 (small models): Whole format
  - Llama 2/3 70B+: Diff format

Code-Specific:
  - CodeLlama (small): Whole/Search format
  - CodeLlama 70B: Diff format
  - DeepSeek Coder: Diff format
  - StarCoder: Whole format
  - WizardCoder: Search/Replace format

# Intelligent Format Recommendation

The package provides smart format selection based on multiple factors:

	// Based on file size
	format := editor.SelectBestFormat("gpt-4", 150*1024) // Large file optimization

	// Based on edit complexity
	format = editor.SelectFormatByComplexity("claude-3-sonnet", editor.ComplexityComplex)

	// Full recommendation with reasoning
	recommendation := editor.RecommendFormat(
	    "gpt-4o",
	    20*1024,                    // 20KB file
	    editor.ComplexityMedium,
	)
	// Returns: FormatRecommendation{
	//   Format: EditFormatDiff,
	//   Confidence: 0.95,
	//   Reasoning: "Small file size, using model's preferred format"
	// }

# Validation

All edits are validated before application:

	// Validate without applying
	if err := editor.ValidateEdit(edit); err != nil {
	    log.Printf("Invalid edit: %v", err)
	    return
	}

	// ApplyEdit also validates
	err := editor.ApplyEdit(edit)

Validation includes:
  - File path verification
  - Format-specific content validation
  - Basic syntax checking for Go, JSON, and YAML files

# Backup Support

Create backups before editing:

	edit := editor.Edit{
	    FilePath: "important.go",
	    Format:   editor.EditFormatWhole,
	    Content:  newContent,
	    Backup:   true, // Creates important.go.bak
	}
	editor.ApplyEdit(edit)

# Custom Validators

Implement custom validation logic:

	type MyValidator struct{}

	func (v *MyValidator) Validate(edit editor.Edit) error {
	    // Custom validation logic
	    return nil
	}

	editor.SetValidator(&MyValidator{})

# Thread Safety

The CodeEditor uses mutex protection for safe concurrent access:

	editor, _ := editor.NewCodeEditor(editor.EditFormatWhole)

	// Safe to call from multiple goroutines
	go editor.ApplyEdit(edit1)
	go editor.ApplyEdit(edit2)

# Performance Considerations

File size guidelines:
  - Small (<10KB): Use preferred format
  - Medium (10-100KB): Use Diff or Search/Replace
  - Large (>100KB): Consider Whole file replacement

Memory usage:
  - Diff: O(n) where n is file size
  - Whole: O(n) where n is new content size
  - Search/Replace: O(n*m) where m is number of operations
  - Lines: O(n) where n is file size

# Testing

The package includes 276+ comprehensive tests covering valid and invalid inputs,
error handling, large file handling (10K+ lines), concurrent editing, and
model format selection.
*/
package editor
