// Package helixagent hosts a HelixCode llm.Provider adapter that routes chat
// completions through a RUNNING HelixAgent server's REST API.
//
// OPERATOR MANDATE: "HelixAgent with all its features MUST be USED in full
// capacity." Rather than re-implementing the 25-provider engine + ensemble
// inside HelixCode, this adapter delegates to the HelixAgent server's
// OpenAI-compatible REST surface (default http://localhost:7061), so HelixCode
// consumes HelixAgent's REAL provider engine, real ensemble, and real model
// catalogue at runtime.
//
// Endpoints used (verified against the running HelixAgent standalone server):
//   - POST {baseURL}/v1/chat/completions  (OpenAI-shape request/response)
//   - GET  {baseURL}/v1/models            (OpenAI-shape {data:[{id,...}]})
//   - GET  {baseURL}/v1/providers          (provider engine roster — liveness)
//
// This package imports dev.helix.code/internal/llm ONLY for the shared
// Provider-interface types. internal/llm never imports this sub-package, so
// there is NO import cycle (mirrors the cerebras/cohere/etc. sub-packages).
//
// CONST-036/037/039: model metadata + the model list are sourced from the live
// /v1/models response — NO hardcoded model list. CONST-046: no user-facing
// hardcoded content is emitted; responses are generated by the remote engine.
package helixagent

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"dev.helix.code/internal/llm"
	"github.com/google/uuid"
)

// Compile-time assertion that *Provider satisfies the shared llm.Provider
// interface. A future edit that drops a method fails the build here rather
// than at a distant caller.
var _ llm.Provider = (*Provider)(nil)

const (
	// DefaultBaseURL is the documented default address of a HelixAgent
	// standalone server. The CALLER resolves the effective base URL from
	// the HELIXAGENT_BASE_URL environment variable and falls back to this
	// constant; this package hardcodes NO URL beyond this documented default.
	DefaultBaseURL = "http://localhost:7061"

	// DefaultModel is the HelixAgent logical model used when LLMRequest.Model
	// is empty. "helixagent-llm" routes through HelixAgent's single-model
	// engine; "helixagent-ensemble" is the verifier-driven ensemble path.
	DefaultModel = "helixagent-llm"

	// EnsembleModel is the logical model that routes through HelixAgent's REAL
	// verifier-driven ensemble. When the caller selects it, Generate hits the
	// server's /v1/ensemble/completions endpoint (which exposes per-member
	// content + model + score), not the single-model /v1/chat/completions path,
	// so the per-member ensemble visibility reaches the operator.
	EnsembleModel = "helixagent-ensemble"

	// providerType is the llm.ProviderType label this adapter reports.
	providerType llm.ProviderType = "helixagent"

	// defaultContextWindow is a conservative large default; HelixAgent fronts
	// many models of varying windows, so we report a safe upper bound.
	defaultContextWindow = 200_000
)

// Provider routes llm.Provider calls through a running HelixAgent REST server.
type Provider struct {
	baseURL    string
	httpClient *http.Client
}

// New constructs a HelixAgent adapter. baseURL is resolved by the CALLER from
// the HELIXAGENT_BASE_URL environment variable (falling back to
// DefaultBaseURL); an empty baseURL here defaults to DefaultBaseURL so the
// adapter is never mis-targeted.
func New(baseURL string) *Provider {
	url := strings.TrimRight(strings.TrimSpace(baseURL), "/")
	if url == "" {
		url = DefaultBaseURL
	}
	return &Provider{
		baseURL: url,
		httpClient: &http.Client{
			Timeout: 120 * time.Second,
			Transport: &http.Transport{
				MaxIdleConns:        100,
				MaxIdleConnsPerHost: 100,
				IdleConnTimeout:     90 * time.Second,
				TLSHandshakeTimeout: 10 * time.Second,
				ForceAttemptHTTP2:   true,
			},
		},
	}
}

// GetType returns the provider type label ("helixagent").
func (p *Provider) GetType() llm.ProviderType { return providerType }

// GetName returns the human-readable provider name.
func (p *Provider) GetName() string { return "HelixAgent" }

// GetCapabilities returns the capability flags this adapter advertises. The
// HelixAgent engine fronts general-purpose chat/code models, so the broad
// text/code/reasoning set is reported.
func (p *Provider) GetCapabilities() []llm.ModelCapability {
	return []llm.ModelCapability{
		llm.CapabilityTextGeneration,
		llm.CapabilityCodeGeneration,
		llm.CapabilityCodeAnalysis,
		llm.CapabilityReasoning,
		llm.CapabilityPlanning,
		llm.CapabilityAnalysis,
	}
}

// GetContextWindow returns a conservative large default context window.
func (p *Provider) GetContextWindow() int { return defaultContextWindow }

// CountTokens returns a char-based estimate (1 token ≈ 4 chars). HelixAgent
// does not expose a tokenize endpoint over its OpenAI-compat surface, so the
// conservative fallback is used per the interface contract.
func (p *Provider) CountTokens(text string) (int, error) {
	if text == "" {
		return 0, nil
	}
	return (len(text) + 3) / 4, nil
}

// Close releases idle connections (no persistent server-side state).
func (p *Provider) Close() error {
	p.httpClient.CloseIdleConnections()
	return nil
}

// ---- OpenAI-compatible wire shapes -----------------------------------------

// wireSendToolCall is the SEND-side on-wire shape of a single assistant
// tool_calls[] entry. Its `function.arguments` is a JSON-encoded STRING — the
// canonical OpenAI/HelixAgent encoding the engine requires; emitting the object
// form (`"arguments":{...}`) is rejected. It is the symmetric inverse of
// wireRecvToolCall (which decodes the same shape on the PARSE side). This
// mirrors internal/llm's unexported wireSendToolCall verbatim; the shared
// helper is not exported from internal/llm, so it is replicated minimally here
// (the only legal option for this sub-package).
type wireSendToolCall struct {
	ID       string `json:"id"`
	Type     string `json:"type"`
	Function struct {
		Name      string `json:"name"`
		Arguments string `json:"arguments"`
	} `json:"function"`
}

// wireRecvToolCall is the PARSE-side on-wire shape: `function.arguments` arrives
// as a JSON STRING (OpenAI canonical), captured as json.RawMessage so
// parseRecvToolCalls can decode both the string-encoded and raw-object forms.
// Mirrors internal/llm's unexported openAIWireToolCall.
type wireRecvToolCall struct {
	ID       string `json:"id"`
	Type     string `json:"type"`
	Function struct {
		Name      string          `json:"name"`
		Arguments json.RawMessage `json:"arguments"`
	} `json:"function"`
}

// toWireSendToolCalls converts []llm.ToolCall into []wireSendToolCall, encoding
// each call's Function.Arguments map as a JSON STRING. A nil/empty arguments map
// (or one that fails to marshal) is encoded as the literal "{}". Returns nil for
// an empty input so plain-chat messages serialise byte-identically with
// omitempty. Mirrors internal/llm's unexported toWireSendToolCalls.
func toWireSendToolCalls(cs []llm.ToolCall) []wireSendToolCall {
	if len(cs) == 0 {
		return nil
	}
	out := make([]wireSendToolCall, 0, len(cs))
	for _, c := range cs {
		args := "{}"
		if len(c.Function.Arguments) > 0 {
			if raw, err := json.Marshal(c.Function.Arguments); err == nil && len(raw) > 0 {
				args = string(raw)
			}
		}
		callType := c.Type
		if callType == "" {
			callType = "function"
		}
		w := wireSendToolCall{ID: c.ID, Type: callType}
		w.Function.Name = c.Function.Name
		w.Function.Arguments = args
		out = append(out, w)
	}
	return out
}

// parseRecvToolCalls converts the wire `tool_calls` array into []llm.ToolCall,
// decoding `function.arguments` whether the engine sent it as a JSON-string
// (OpenAI canonical, e.g. "{\"path\":\".\"}") or a raw JSON object. Returns nil
// for an empty array so plain-chat responses are unchanged. Mirrors
// internal/llm's unexported parseOpenAIWireToolCalls.
func parseRecvToolCalls(wire []wireRecvToolCall) []llm.ToolCall {
	if len(wire) == 0 {
		return nil
	}
	out := make([]llm.ToolCall, 0, len(wire))
	for _, w := range wire {
		args := map[string]interface{}{}
		if raw := []byte(w.Function.Arguments); len(raw) > 0 {
			var asString string
			if err := json.Unmarshal(raw, &asString); err == nil {
				if asString != "" {
					if uerr := json.Unmarshal([]byte(asString), &args); uerr != nil {
						args = map[string]interface{}{}
					}
				}
			} else if uerr := json.Unmarshal(raw, &args); uerr != nil {
				args = map[string]interface{}{}
			}
		}
		callType := w.Type
		if callType == "" {
			callType = "function"
		}
		out = append(out, llm.ToolCall{
			ID:   w.ID,
			Type: callType,
			Function: llm.ToolCallFunc{
				Name:      w.Function.Name,
				Arguments: args,
			},
		})
	}
	return out
}

// chatMessage is the on-wire message shape. ToolCallID is REQUIRED on every
// role:"tool" result message; ToolCalls (assistant turns) serialise
// function.arguments as a JSON STRING via toWireSendToolCalls. omitempty ⇒
// plain-chat messages serialise byte-identically.
type chatMessage struct {
	Role       string             `json:"role"`
	Content    string             `json:"content"`
	Name       string             `json:"name,omitempty"`
	ToolCallID string             `json:"tool_call_id,omitempty"`
	ToolCalls  []wireSendToolCall `json:"tool_calls,omitempty"`
}

type chatRequest struct {
	Model       string        `json:"model"`
	Messages    []chatMessage `json:"messages"`
	Stream      bool          `json:"stream,omitempty"`
	Temperature float64       `json:"temperature,omitempty"`
	MaxTokens   int           `json:"max_tokens,omitempty"`
	// Tools + ToolChoice are forwarded only when request.Tools is non-empty so
	// plain-chat requests stay byte-identical (omitempty). Tools reuses
	// llm.Tool verbatim (the OpenAI tool-definition shape the engine expects).
	Tools      []llm.Tool  `json:"tools,omitempty"`
	ToolChoice interface{} `json:"tool_choice,omitempty"`
}

type chatUsage struct {
	PromptTokens     int `json:"prompt_tokens"`
	CompletionTokens int `json:"completion_tokens"`
	TotalTokens      int `json:"total_tokens"`
}

type chatResponse struct {
	ID      string `json:"id"`
	Model   string `json:"model"`
	Choices []struct {
		Index   int `json:"index"`
		Message struct {
			Role      string             `json:"role"`
			Content   string             `json:"content"`
			ToolCalls []wireRecvToolCall `json:"tool_calls,omitempty"`
		} `json:"message"`
		FinishReason string `json:"finish_reason"`
	} `json:"choices"`
	Usage chatUsage `json:"usage"`
	Error *struct {
		Message string `json:"message"`
	} `json:"error,omitempty"`
	// Ensemble is present ONLY on responses from the server's
	// /v1/ensemble/completions endpoint. It carries the per-member visibility
	// data (each member's content + the model it served + its score + whether it
	// won) so the HelixCode TUI can render the SAME ensemble panel for the
	// HelixAgent ensemble as for the local ensemble. Absent (nil) on ordinary
	// /v1/chat/completions responses.
	Ensemble *ensembleEnvelope `json:"ensemble,omitempty"`
}

// ensembleEnvelope mirrors the HelixAgent server's /v1/ensemble/completions
// `ensemble` JSON object (router.go). Decoupled DTO — it models only the fields
// the TUI panel consumes.
type ensembleEnvelope struct {
	VotingMethod     string             `json:"voting_method"`
	ResponsesCount   int                `json:"responses_count"`
	SelectedProvider string             `json:"selected_provider"`
	NameScores       map[string]float64 `json:"name_scores"`
	Members          []ensembleMember   `json:"members"`
}

// ensembleMember mirrors one entry of the server's ensemble.members[] array:
// the participating provider's name, the model it served (chosen via
// LLMsVerifier), its produced content, its score, and whether it was selected.
type ensembleMember struct {
	ProviderName   string  `json:"provider_name"`
	Model          string  `json:"model"`
	Content        string  `json:"content"`
	Confidence     float64 `json:"confidence"`
	SelectionScore float64 `json:"selection_score"`
	Selected       bool    `json:"selected"`
}

type chatStreamChunk struct {
	Choices []struct {
		Delta struct {
			Content   string             `json:"content"`
			ToolCalls []wireRecvToolCall `json:"tool_calls,omitempty"`
		} `json:"delta"`
		FinishReason string `json:"finish_reason"`
	} `json:"choices"`
	Usage *chatUsage `json:"usage,omitempty"`
}

type modelsResponse struct {
	Data []struct {
		ID string `json:"id"`
	} `json:"data"`
}

// ---- request mapping --------------------------------------------------------

func (p *Provider) buildChatRequest(request *llm.LLMRequest, stream bool) chatRequest {
	model := strings.TrimSpace(request.Model)
	if model == "" {
		model = DefaultModel
	}
	// Serialise each message verbatim — including role:"tool" result messages
	// (ToolCallID set) and assistant turns carrying tool_calls (arguments encoded
	// as a JSON STRING via toWireSendToolCalls). This preserves the full
	// tool-conversation protocol the TUI tool loop (internal/agent.RunToolLoop)
	// feeds back across turns.
	msgs := make([]chatMessage, 0, len(request.Messages))
	for _, m := range request.Messages {
		toolCalls := toWireSendToolCalls(m.ToolCalls)
		content := m.Content
		// HelixAgent enforces "an assistant message MUST have content or
		// tool_calls" and rejects the whole request (HTTP 400,
		// "messages[N]: assistant message must have content or tool_calls")
		// BEFORE provider dispatch when an assistant message arrives with BOTH
		// empty content AND no tool_calls. Such a message is a real outcome of a
		// multi-prompt conversation: any caller (the TUI's chatHistory, a
		// streaming-final turn that emitted no text, an ensemble panel that
		// produced no lines) can store an empty assistant turn, and once it is
		// replayed in the history of the NEXT request the strict server 400s the
		// entire conversation — breaking every subsequent prompt. Sanitize at the
		// wire layer so the adapter is tolerant of ANY caller: an assistant
		// message with empty content and no tool_calls gets a single-space
		// content placeholder (the minimal non-empty content the server
		// accepts), which satisfies the "content or tool_calls" rule without
		// altering the semantics of the turn. Only the assistant role is
		// affected; user/system/tool messages are serialized verbatim (a tool
		// result legitimately has empty content paired with its tool_call_id, and
		// user/system messages are never empty in practice).
		if m.Role == "assistant" && strings.TrimSpace(content) == "" && len(toolCalls) == 0 {
			content = " "
		}
		msgs = append(msgs, chatMessage{
			Role:       m.Role,
			Content:    content,
			Name:       m.Name,
			ToolCallID: m.ToolCallID,
			ToolCalls:  toolCalls,
		})
	}
	cr := chatRequest{
		Model:       model,
		Messages:    msgs,
		Stream:      stream,
		Temperature: request.Temperature,
		MaxTokens:   request.MaxTokens,
	}
	// Forward tools + tool_choice only when the caller supplied tools, so plain
	// chat requests stay byte-identical on the wire (omitempty).
	if len(request.Tools) > 0 {
		cr.Tools = request.Tools
		cr.ToolChoice = request.ToolChoice
	}
	return cr
}

// Generate sends a non-streaming chat completion to the running HelixAgent
// server and maps the OpenAI-shape response back to an llm.LLMResponse.
func (p *Provider) Generate(ctx context.Context, request *llm.LLMRequest) (*llm.LLMResponse, error) {
	start := time.Now()
	body, err := json.Marshal(p.buildChatRequest(request, false))
	if err != nil {
		return nil, fmt.Errorf("helixagent: marshal request: %w", err)
	}

	// Route the verifier-driven ensemble model through the server's ensemble
	// endpoint, which exposes per-member content + model + score. Every other
	// model uses the single-model chat endpoint. The chat-request body shape is
	// accepted by both endpoints (the ensemble handler binds the same
	// messages/model/temperature fields).
	endpoint := "/v1/chat/completions"
	if strings.TrimSpace(request.Model) == EnsembleModel {
		endpoint = "/v1/ensemble/completions"
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, p.baseURL+endpoint, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("helixagent: build http request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := p.httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("helixagent: POST /v1/chat/completions: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("helixagent: read response body: %w", err)
	}
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("helixagent: completion failed (HTTP %d) at %s: %s", resp.StatusCode, endpoint, strings.TrimSpace(string(raw)))
	}

	var cr chatResponse
	if err := json.Unmarshal(raw, &cr); err != nil {
		return nil, fmt.Errorf("helixagent: decode response: %w", err)
	}
	if cr.Error != nil && cr.Error.Message != "" {
		return nil, fmt.Errorf("helixagent: engine error: %s", cr.Error.Message)
	}

	var content, finishReason string
	var toolCalls []llm.ToolCall
	if len(cr.Choices) > 0 {
		content = cr.Choices[0].Message.Content
		finishReason = cr.Choices[0].FinishReason
		// An assistant message with empty content + tool_calls is valid: the
		// engine requested tool execution. parseRecvToolCalls returns nil for an
		// absent array so plain-chat responses keep ToolCalls nil.
		toolCalls = parseRecvToolCalls(cr.Choices[0].Message.ToolCalls)
	}

	meta := map[string]interface{}{
		"helixagent_model": cr.Model,
	}
	// When the server returned ensemble data (the /v1/ensemble/completions
	// path), translate it into the EXACT metadata keys the HelixCode TUI panel
	// (applications/terminal_ui.FormatEnsemblePanel) consumes — so the HelixAgent
	// ensemble renders with per-member content + per-member model + scores +
	// winner, identical to the local ensemble, with NO TUI change.
	if cr.Ensemble != nil && len(cr.Ensemble.Members) > 0 {
		populateEnsembleMetadata(meta, cr.Ensemble)
	}

	return &llm.LLMResponse{
		ID:        uuid.New(),
		RequestID: request.ID,
		Content:   content,
		ToolCalls: toolCalls,
		Usage: llm.Usage{
			PromptTokens:     cr.Usage.PromptTokens,
			CompletionTokens: cr.Usage.CompletionTokens,
			TotalTokens:      cr.Usage.TotalTokens,
		},
		FinishReason:     finishReason,
		ProcessingTime:   time.Since(start),
		CreatedAt:        time.Now(),
		ProviderMetadata: meta,
	}, nil
}

// ensembleExcerptMaxRunes bounds each member's content excerpt in the panel
// metadata so a verbose member answer cannot blow up the rendered panel.
const ensembleExcerptMaxRunes = 160

// populateEnsembleMetadata writes the per-member ensemble visibility data into
// meta using the EXACT keys FormatEnsemblePanel reads, so the HelixAgent
// ensemble shares the local ensemble's renderer verbatim.
func populateEnsembleMetadata(meta map[string]interface{}, env *ensembleEnvelope) {
	participants := make([]string, 0, len(env.Members))
	scores := make(map[string]float64, len(env.Members))
	excerpts := make(map[string]string, len(env.Members))
	models := make(map[string]string, len(env.Members))
	successful := 0
	for _, m := range env.Members {
		name := strings.TrimSpace(m.ProviderName)
		if name == "" {
			continue
		}
		participants = append(participants, name)
		scores[name] = m.SelectionScore
		excerpts[name] = excerptRunes(m.Content, ensembleExcerptMaxRunes)
		if mdl := strings.TrimSpace(m.Model); mdl != "" {
			models[name] = mdl
		}
		successful++
	}

	meta["ensemble"] = true
	meta["ensemble_strategy"] = env.VotingMethod
	meta["ensemble_total_providers"] = env.ResponsesCount
	meta["ensemble_successful_providers"] = successful
	meta["ensemble_selected_provider"] = env.SelectedProvider
	meta["ensemble_participants"] = participants
	meta["ensemble_scores"] = scores
	meta["ensemble_excerpts"] = excerpts
	meta["ensemble_models"] = models
}

// excerptRunes returns up to n runes of s (trimmed), appending an ellipsis when
// truncated. Mirrors the local ensemble's excerpt helper so both panels render
// consistently.
func excerptRunes(s string, n int) string {
	s = strings.TrimSpace(s)
	r := []rune(s)
	if len(r) <= n {
		return s
	}
	return string(r[:n]) + "…"
}

// GenerateStream sends a streaming chat completion and emits one llm.LLMResponse
// per SSE `data:` chunk on ch, closing ch at `[DONE]` (or on completion). It
// mirrors the SSE-parsing pattern of the in-tree Groq provider.
func (p *Provider) GenerateStream(ctx context.Context, request *llm.LLMRequest, ch chan<- llm.LLMResponse) error {
	defer close(ch)
	start := time.Now()

	body, err := json.Marshal(p.buildChatRequest(request, true))
	if err != nil {
		return fmt.Errorf("helixagent: marshal stream request: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, p.baseURL+"/v1/chat/completions", bytes.NewReader(body))
	if err != nil {
		return fmt.Errorf("helixagent: build http stream request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "text/event-stream")

	resp, err := p.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("helixagent: POST /v1/chat/completions (stream): %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		raw, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("helixagent: stream failed (HTTP %d): %s", resp.StatusCode, strings.TrimSpace(string(raw)))
	}

	scanner := bufio.NewScanner(resp.Body)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		if !strings.HasPrefix(line, "data:") {
			continue
		}
		data := strings.TrimSpace(strings.TrimPrefix(line, "data:"))
		if data == "" {
			continue
		}
		if data == "[DONE]" {
			break
		}

		var chunk chatStreamChunk
		if err := json.Unmarshal([]byte(data), &chunk); err != nil {
			// Skip malformed/keepalive frames rather than aborting the stream.
			continue
		}
		if len(chunk.Choices) == 0 {
			continue
		}

		delta := chunk.Choices[0].Delta.Content
		finishReason := chunk.Choices[0].FinishReason
		// Tool-call deltas (engine streamed a tool request). Each frame carrying
		// tool_calls is surfaced so a streaming tool-loop consumer sees them;
		// parseRecvToolCalls returns nil for plain-text deltas. The engine
		// commonly sends complete tool_calls (id+name+arguments) in the frame
		// preceding finish_reason:"tool_calls" rather than fragmenting them.
		toolCalls := parseRecvToolCalls(chunk.Choices[0].Delta.ToolCalls)

		if delta != "" || len(toolCalls) > 0 {
			ch <- llm.LLMResponse{
				ID:        uuid.New(),
				RequestID: request.ID,
				Content:   delta,
				ToolCalls: toolCalls,
				CreatedAt: time.Now(),
			}
		}

		if finishReason != "" {
			final := llm.LLMResponse{
				ID:             uuid.New(),
				RequestID:      request.ID,
				Content:        "",
				FinishReason:   finishReason,
				ProcessingTime: time.Since(start),
				CreatedAt:      time.Now(),
			}
			if chunk.Usage != nil {
				final.Usage = llm.Usage{
					PromptTokens:     chunk.Usage.PromptTokens,
					CompletionTokens: chunk.Usage.CompletionTokens,
					TotalTokens:      chunk.Usage.TotalTokens,
				}
			}
			ch <- final
		}
	}

	return scanner.Err()
}

// GetModels queries the live /v1/models endpoint and maps every served model
// id to an llm.ModelInfo. The list is sourced ENTIRELY from the running
// HelixAgent server (CONST-036/037 — no hardcoded model list). When the server
// is unreachable an empty slice is returned (callers should consult
// IsAvailable/GetHealth for liveness).
func (p *Provider) GetModels() []llm.ModelInfo {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	models, err := p.fetchModels(ctx)
	if err != nil {
		return nil
	}
	return models
}

func (p *Provider) fetchModels(ctx context.Context) ([]llm.ModelInfo, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, p.baseURL+"/v1/models", nil)
	if err != nil {
		return nil, err
	}
	resp, err := p.httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("helixagent: GET /v1/models HTTP %d", resp.StatusCode)
	}

	var mr modelsResponse
	if err := json.NewDecoder(resp.Body).Decode(&mr); err != nil {
		return nil, err
	}

	out := make([]llm.ModelInfo, 0, len(mr.Data))
	for _, m := range mr.Data {
		if strings.TrimSpace(m.ID) == "" {
			continue
		}
		out = append(out, llm.ModelInfo{
			ID:          m.ID,
			Name:        m.ID,
			Provider:    providerType,
			ContextSize: defaultContextWindow,
			Capabilities: []llm.ModelCapability{
				llm.CapabilityTextGeneration,
				llm.CapabilityCodeGeneration,
			},
			Description: fmt.Sprintf("HelixAgent logical model %q served by the HelixAgent engine", m.ID),
			Metadata: map[string]interface{}{
				"source": "helixagent:/v1/models",
			},
		})
	}
	return out, nil
}

// IsAvailable reports whether the HelixAgent server is reachable and exposing
// at least one provider in its engine roster (GET /v1/providers).
func (p *Provider) IsAvailable(ctx context.Context) bool {
	n, err := p.providerCount(ctx)
	return err == nil && n >= 1
}

// GetHealth probes /v1/providers and reports healthy when the server is
// reachable with ≥1 provider in its engine roster.
func (p *Provider) GetHealth(ctx context.Context) (*llm.ProviderHealth, error) {
	start := time.Now()
	health := &llm.ProviderHealth{LastCheck: time.Now()}

	n, err := p.providerCount(ctx)
	health.Latency = time.Since(start)
	if err != nil {
		health.Status = "unhealthy"
		health.ErrorCount = 1
		health.Message = fmt.Sprintf("HelixAgent unreachable at %s: %v", p.baseURL, err)
		return health, err
	}
	if n < 1 {
		health.Status = "unhealthy"
		health.ErrorCount = 1
		health.Message = fmt.Sprintf("HelixAgent at %s reports zero providers", p.baseURL)
		return health, fmt.Errorf("helixagent: zero providers in engine roster")
	}

	health.Status = "healthy"
	health.Message = fmt.Sprintf("HelixAgent reachable at %s with %d providers", p.baseURL, n)
	if models := p.GetModels(); models != nil {
		health.ModelCount = len(models)
	}
	return health, nil
}

// providerCount returns the number of providers in the HelixAgent engine
// roster. It accepts both an array-shaped and an object-wrapped
// ({"providers":[...]} / {"data":[...]}) response so it is resilient to the
// exact /v1/providers envelope.
func (p *Provider) providerCount(ctx context.Context) (int, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, p.baseURL+"/v1/providers", nil)
	if err != nil {
		return 0, err
	}
	resp, err := p.httpClient.Do(req)
	if err != nil {
		return 0, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return 0, fmt.Errorf("helixagent: GET /v1/providers HTTP %d", resp.StatusCode)
	}

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return 0, err
	}

	// Try array shape first: [ {...}, {...} ].
	var asArray []json.RawMessage
	if json.Unmarshal(raw, &asArray) == nil && len(asArray) > 0 {
		return len(asArray), nil
	}

	// Object-wrapped shapes: {"providers":[...]} or {"data":[...]}.
	var wrapped struct {
		Providers []json.RawMessage `json:"providers"`
		Data      []json.RawMessage `json:"data"`
	}
	if json.Unmarshal(raw, &wrapped) == nil {
		if n := len(wrapped.Providers); n > 0 {
			return n, nil
		}
		if n := len(wrapped.Data); n > 0 {
			return n, nil
		}
	}

	// Reachable but empty roster.
	return 0, nil
}
