// Package helixagent hosts a HelixCode llm.Provider adapter that routes chat
// completions through a RUNNING HelixAgent server's REST API.
//
// OPERATOR MANDATE: "HelixAgent with all its features MUST be USED in full
// capacity." Rather than re-implementing the 25-provider engine + ensemble
// inside HelixCode, this adapter delegates to the HelixAgent server's
// OpenAI-compatible REST surface (default http://localhost:7061), so HelixCode
// consumes HelixAgent's REAL provider engine, real ensemble, and real model
// catalogue at runtime.
//
// Endpoints used (verified against the running HelixAgent standalone server):
//   - POST {baseURL}/v1/chat/completions  (OpenAI-shape request/response)
//   - GET  {baseURL}/v1/models            (OpenAI-shape {data:[{id,...}]})
//   - GET  {baseURL}/v1/providers          (provider engine roster — liveness)
//
// This package imports dev.helix.code/internal/llm ONLY for the shared
// Provider-interface types. internal/llm never imports this sub-package, so
// there is NO import cycle (mirrors the cerebras/cohere/etc. sub-packages).
//
// CONST-036/037/039: model metadata + the model list are sourced from the live
// /v1/models response — NO hardcoded model list. CONST-046: no user-facing
// hardcoded content is emitted; responses are generated by the remote engine.
package helixagent

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"dev.helix.code/internal/llm"
	"github.com/google/uuid"
)

// Compile-time assertion that *Provider satisfies the shared llm.Provider
// interface. A future edit that drops a method fails the build here rather
// than at a distant caller.
var _ llm.Provider = (*Provider)(nil)

const (
	// DefaultBaseURL is the documented default address of a HelixAgent
	// standalone server. The CALLER resolves the effective base URL from
	// the HELIXAGENT_BASE_URL environment variable and falls back to this
	// constant; this package hardcodes NO URL beyond this documented default.
	DefaultBaseURL = "http://localhost:7061"

	// DefaultModel is the HelixAgent logical model used when LLMRequest.Model
	// is empty. "helixagent-llm" routes through HelixAgent's single-model
	// engine; "helixagent-ensemble" is the verifier-driven ensemble path.
	DefaultModel = "helixagent-llm"

	// providerType is the llm.ProviderType label this adapter reports.
	providerType llm.ProviderType = "helixagent"

	// defaultContextWindow is a conservative large default; HelixAgent fronts
	// many models of varying windows, so we report a safe upper bound.
	defaultContextWindow = 200_000
)

// Provider routes llm.Provider calls through a running HelixAgent REST server.
type Provider struct {
	baseURL    string
	httpClient *http.Client
}

// New constructs a HelixAgent adapter. baseURL is resolved by the CALLER from
// the HELIXAGENT_BASE_URL environment variable (falling back to
// DefaultBaseURL); an empty baseURL here defaults to DefaultBaseURL so the
// adapter is never mis-targeted.
func New(baseURL string) *Provider {
	url := strings.TrimRight(strings.TrimSpace(baseURL), "/")
	if url == "" {
		url = DefaultBaseURL
	}
	return &Provider{
		baseURL: url,
		httpClient: &http.Client{
			Timeout: 120 * time.Second,
			Transport: &http.Transport{
				MaxIdleConns:        100,
				MaxIdleConnsPerHost: 100,
				IdleConnTimeout:     90 * time.Second,
				TLSHandshakeTimeout: 10 * time.Second,
				ForceAttemptHTTP2:   true,
			},
		},
	}
}

// GetType returns the provider type label ("helixagent").
func (p *Provider) GetType() llm.ProviderType { return providerType }

// GetName returns the human-readable provider name.
func (p *Provider) GetName() string { return "HelixAgent" }

// GetCapabilities returns the capability flags this adapter advertises. The
// HelixAgent engine fronts general-purpose chat/code models, so the broad
// text/code/reasoning set is reported.
func (p *Provider) GetCapabilities() []llm.ModelCapability {
	return []llm.ModelCapability{
		llm.CapabilityTextGeneration,
		llm.CapabilityCodeGeneration,
		llm.CapabilityCodeAnalysis,
		llm.CapabilityReasoning,
		llm.CapabilityPlanning,
		llm.CapabilityAnalysis,
	}
}

// GetContextWindow returns a conservative large default context window.
func (p *Provider) GetContextWindow() int { return defaultContextWindow }

// CountTokens returns a char-based estimate (1 token ≈ 4 chars). HelixAgent
// does not expose a tokenize endpoint over its OpenAI-compat surface, so the
// conservative fallback is used per the interface contract.
func (p *Provider) CountTokens(text string) (int, error) {
	if text == "" {
		return 0, nil
	}
	return (len(text) + 3) / 4, nil
}

// Close releases idle connections (no persistent server-side state).
func (p *Provider) Close() error {
	p.httpClient.CloseIdleConnections()
	return nil
}

// ---- OpenAI-compatible wire shapes -----------------------------------------

type chatMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
	Name    string `json:"name,omitempty"`
}

type chatRequest struct {
	Model       string        `json:"model"`
	Messages    []chatMessage `json:"messages"`
	Stream      bool          `json:"stream,omitempty"`
	Temperature float64       `json:"temperature,omitempty"`
	MaxTokens   int           `json:"max_tokens,omitempty"`
}

type chatUsage struct {
	PromptTokens     int `json:"prompt_tokens"`
	CompletionTokens int `json:"completion_tokens"`
	TotalTokens      int `json:"total_tokens"`
}

type chatResponse struct {
	ID      string `json:"id"`
	Model   string `json:"model"`
	Choices []struct {
		Index   int `json:"index"`
		Message struct {
			Role    string `json:"role"`
			Content string `json:"content"`
		} `json:"message"`
		FinishReason string `json:"finish_reason"`
	} `json:"choices"`
	Usage chatUsage `json:"usage"`
	Error *struct {
		Message string `json:"message"`
	} `json:"error,omitempty"`
}

type chatStreamChunk struct {
	Choices []struct {
		Delta struct {
			Content string `json:"content"`
		} `json:"delta"`
		FinishReason string `json:"finish_reason"`
	} `json:"choices"`
	Usage *chatUsage `json:"usage,omitempty"`
}

type modelsResponse struct {
	Data []struct {
		ID string `json:"id"`
	} `json:"data"`
}

// ---- request mapping --------------------------------------------------------

func (p *Provider) buildChatRequest(request *llm.LLMRequest, stream bool) chatRequest {
	model := strings.TrimSpace(request.Model)
	if model == "" {
		model = DefaultModel
	}
	msgs := make([]chatMessage, 0, len(request.Messages))
	for _, m := range request.Messages {
		msgs = append(msgs, chatMessage{Role: m.Role, Content: m.Content, Name: m.Name})
	}
	return chatRequest{
		Model:       model,
		Messages:    msgs,
		Stream:      stream,
		Temperature: request.Temperature,
		MaxTokens:   request.MaxTokens,
	}
}

// Generate sends a non-streaming chat completion to the running HelixAgent
// server and maps the OpenAI-shape response back to an llm.LLMResponse.
func (p *Provider) Generate(ctx context.Context, request *llm.LLMRequest) (*llm.LLMResponse, error) {
	start := time.Now()
	body, err := json.Marshal(p.buildChatRequest(request, false))
	if err != nil {
		return nil, fmt.Errorf("helixagent: marshal request: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, p.baseURL+"/v1/chat/completions", bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("helixagent: build http request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := p.httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("helixagent: POST /v1/chat/completions: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("helixagent: read response body: %w", err)
	}
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("helixagent: chat completion failed (HTTP %d): %s", resp.StatusCode, strings.TrimSpace(string(raw)))
	}

	var cr chatResponse
	if err := json.Unmarshal(raw, &cr); err != nil {
		return nil, fmt.Errorf("helixagent: decode response: %w", err)
	}
	if cr.Error != nil && cr.Error.Message != "" {
		return nil, fmt.Errorf("helixagent: engine error: %s", cr.Error.Message)
	}

	var content, finishReason string
	if len(cr.Choices) > 0 {
		content = cr.Choices[0].Message.Content
		finishReason = cr.Choices[0].FinishReason
	}

	return &llm.LLMResponse{
		ID:        uuid.New(),
		RequestID: request.ID,
		Content:   content,
		Usage: llm.Usage{
			PromptTokens:     cr.Usage.PromptTokens,
			CompletionTokens: cr.Usage.CompletionTokens,
			TotalTokens:      cr.Usage.TotalTokens,
		},
		FinishReason:   finishReason,
		ProcessingTime: time.Since(start),
		CreatedAt:      time.Now(),
		ProviderMetadata: map[string]interface{}{
			"helixagent_model": cr.Model,
		},
	}, nil
}

// GenerateStream sends a streaming chat completion and emits one llm.LLMResponse
// per SSE `data:` chunk on ch, closing ch at `[DONE]` (or on completion). It
// mirrors the SSE-parsing pattern of the in-tree Groq provider.
func (p *Provider) GenerateStream(ctx context.Context, request *llm.LLMRequest, ch chan<- llm.LLMResponse) error {
	defer close(ch)
	start := time.Now()

	body, err := json.Marshal(p.buildChatRequest(request, true))
	if err != nil {
		return fmt.Errorf("helixagent: marshal stream request: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, p.baseURL+"/v1/chat/completions", bytes.NewReader(body))
	if err != nil {
		return fmt.Errorf("helixagent: build http stream request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "text/event-stream")

	resp, err := p.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("helixagent: POST /v1/chat/completions (stream): %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		raw, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("helixagent: stream failed (HTTP %d): %s", resp.StatusCode, strings.TrimSpace(string(raw)))
	}

	scanner := bufio.NewScanner(resp.Body)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		if !strings.HasPrefix(line, "data:") {
			continue
		}
		data := strings.TrimSpace(strings.TrimPrefix(line, "data:"))
		if data == "" {
			continue
		}
		if data == "[DONE]" {
			break
		}

		var chunk chatStreamChunk
		if err := json.Unmarshal([]byte(data), &chunk); err != nil {
			// Skip malformed/keepalive frames rather than aborting the stream.
			continue
		}
		if len(chunk.Choices) == 0 {
			continue
		}

		delta := chunk.Choices[0].Delta.Content
		finishReason := chunk.Choices[0].FinishReason

		if delta != "" {
			ch <- llm.LLMResponse{
				ID:        uuid.New(),
				RequestID: request.ID,
				Content:   delta,
				CreatedAt: time.Now(),
			}
		}

		if finishReason != "" {
			final := llm.LLMResponse{
				ID:             uuid.New(),
				RequestID:      request.ID,
				Content:        "",
				FinishReason:   finishReason,
				ProcessingTime: time.Since(start),
				CreatedAt:      time.Now(),
			}
			if chunk.Usage != nil {
				final.Usage = llm.Usage{
					PromptTokens:     chunk.Usage.PromptTokens,
					CompletionTokens: chunk.Usage.CompletionTokens,
					TotalTokens:      chunk.Usage.TotalTokens,
				}
			}
			ch <- final
		}
	}

	return scanner.Err()
}

// GetModels queries the live /v1/models endpoint and maps every served model
// id to an llm.ModelInfo. The list is sourced ENTIRELY from the running
// HelixAgent server (CONST-036/037 — no hardcoded model list). When the server
// is unreachable an empty slice is returned (callers should consult
// IsAvailable/GetHealth for liveness).
func (p *Provider) GetModels() []llm.ModelInfo {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	models, err := p.fetchModels(ctx)
	if err != nil {
		return nil
	}
	return models
}

func (p *Provider) fetchModels(ctx context.Context) ([]llm.ModelInfo, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, p.baseURL+"/v1/models", nil)
	if err != nil {
		return nil, err
	}
	resp, err := p.httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("helixagent: GET /v1/models HTTP %d", resp.StatusCode)
	}

	var mr modelsResponse
	if err := json.NewDecoder(resp.Body).Decode(&mr); err != nil {
		return nil, err
	}

	out := make([]llm.ModelInfo, 0, len(mr.Data))
	for _, m := range mr.Data {
		if strings.TrimSpace(m.ID) == "" {
			continue
		}
		out = append(out, llm.ModelInfo{
			ID:          m.ID,
			Name:        m.ID,
			Provider:    providerType,
			ContextSize: defaultContextWindow,
			Capabilities: []llm.ModelCapability{
				llm.CapabilityTextGeneration,
				llm.CapabilityCodeGeneration,
			},
			Description: fmt.Sprintf("HelixAgent logical model %q served by the HelixAgent engine", m.ID),
			Metadata: map[string]interface{}{
				"source": "helixagent:/v1/models",
			},
		})
	}
	return out, nil
}

// IsAvailable reports whether the HelixAgent server is reachable and exposing
// at least one provider in its engine roster (GET /v1/providers).
func (p *Provider) IsAvailable(ctx context.Context) bool {
	n, err := p.providerCount(ctx)
	return err == nil && n >= 1
}

// GetHealth probes /v1/providers and reports healthy when the server is
// reachable with ≥1 provider in its engine roster.
func (p *Provider) GetHealth(ctx context.Context) (*llm.ProviderHealth, error) {
	start := time.Now()
	health := &llm.ProviderHealth{LastCheck: time.Now()}

	n, err := p.providerCount(ctx)
	health.Latency = time.Since(start)
	if err != nil {
		health.Status = "unhealthy"
		health.ErrorCount = 1
		health.Message = fmt.Sprintf("HelixAgent unreachable at %s: %v", p.baseURL, err)
		return health, err
	}
	if n < 1 {
		health.Status = "unhealthy"
		health.ErrorCount = 1
		health.Message = fmt.Sprintf("HelixAgent at %s reports zero providers", p.baseURL)
		return health, fmt.Errorf("helixagent: zero providers in engine roster")
	}

	health.Status = "healthy"
	health.Message = fmt.Sprintf("HelixAgent reachable at %s with %d providers", p.baseURL, n)
	if models := p.GetModels(); models != nil {
		health.ModelCount = len(models)
	}
	return health, nil
}

// providerCount returns the number of providers in the HelixAgent engine
// roster. It accepts both an array-shaped and an object-wrapped
// ({"providers":[...]} / {"data":[...]}) response so it is resilient to the
// exact /v1/providers envelope.
func (p *Provider) providerCount(ctx context.Context) (int, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, p.baseURL+"/v1/providers", nil)
	if err != nil {
		return 0, err
	}
	resp, err := p.httpClient.Do(req)
	if err != nil {
		return 0, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return 0, fmt.Errorf("helixagent: GET /v1/providers HTTP %d", resp.StatusCode)
	}

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return 0, err
	}

	// Try array shape first: [ {...}, {...} ].
	var asArray []json.RawMessage
	if json.Unmarshal(raw, &asArray) == nil && len(asArray) > 0 {
		return len(asArray), nil
	}

	// Object-wrapped shapes: {"providers":[...]} or {"data":[...]}.
	var wrapped struct {
		Providers []json.RawMessage `json:"providers"`
		Data      []json.RawMessage `json:"data"`
	}
	if json.Unmarshal(raw, &wrapped) == nil {
		if n := len(wrapped.Providers); n > 0 {
			return n, nil
		}
		if n := len(wrapped.Data); n > 0 {
			return n, nil
		}
	}

	// Reachable but empty roster.
	return 0, nil
}
