#!/usr/bin/env bash
# generate_features_summary.sh — docs_chain transform: Status_Summary.md from inventory rollup.
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"; cd "$root"
inv=docs/features/inventory
feat=$(cat $inv/*.md | grep -cE '^\| ' || true)
wu=$(cat $inv/*.md | grep -oiE '\bworking-untaped\b' | wc -l | tr -d ' ')
pa=$(cat $inv/*.md | grep -oiE '\bpartial\b' | wc -l | tr -d ' ')
gp=$(cat $inv/*.md | grep -oiE '\bgap\b' | wc -l | tr -d ' ')
vids=$(ls /Volumes/T7/Downloads/Recordings/helixcode-*.mp4 2>/dev/null | wc -l | tr -d ' ')
out() {
cat <<EOF
# HelixCode Feature Status — Summary

| | |
|---|---|
| Revision | 2 |
| Created | 2026-06-15 |
| Last modified | 2026-06-15 |
| Status | active (generated by scripts/generate_features_summary.sh) |
| Status detail | docs/features/Status.md |

Auto-generated rollup of docs/features/Status.md (docs_chain §11.4.106). Anti-bluff:
video-confirmed rises only as real analyzed recordings land in
/Volumes/T7/Downloads/Recordings (§11.4.83/§11.4.107).

## Rollup

| Metric | Value |
|---|---|
| Total inventory rows | ${feat} |
| working-untaped (mentions) | ${wu} |
| partial (mentions) | ${pa} |
| gap (mentions) | ${gp} |
| confirmed (real analyzed video) | 0 until videos land |
| helixcode-*.mp4 recordings produced so far | ${vids} |

See docs/features/Status.md for the full per-feature table.
EOF
}
if [ "${1:-}" = "--stdout" ]; then out; else out > docs/features/Status_Summary.md; fi
